# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += imx8mm-edm-g.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-edm-g-wb.dtb

dtb-$(CONFIG_ARCH_MXC) += imx8mp-edm-g.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mp-edm-g-wb.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-reh.dtb
dtb-$(CONFIG_ARCH_MXC) += imx8mm-facscope.dtb

# enable creation of __symbols__ node
DTC_FLAGS_imx8mm-edm-g-wb := -@
DTC_FLAGS_imx8mp-edm-g-wb := -@
